name: Lint and Test

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
      - uses: actions/checkout@v2
      - run: npm audit
      - run: npm ci
      - run: npm run lint
      - run: npm test
