name: Lint and Test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - run: npm ci
      - run: npm run lint
      - run: npm test
